{{- if not .Values.secrets.existingSecret }}
{{- $existingAppSecret := lookup "v1" "Secret" .Release.Namespace (include "open-tappd.fullname" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "open-tappd.fullname" . }}
  labels:
    {{- include "open-tappd.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.encryptionKey }}
  encryption-key: {{ .Values.secrets.encryptionKey | b64enc | quote }}
  {{- else if and $existingAppSecret (index $existingAppSecret.data "encryption-key") }}
  encryption-key: {{ index $existingAppSecret.data "encryption-key" }}
  {{- else }}
  encryption-key: {{ randAlphaNum 32 | b64enc | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.jwtSecret }}
  jwt-secret: {{ .Values.secrets.jwtSecret | b64enc | quote }}
  {{- else if and $existingAppSecret (index $existingAppSecret.data "jwt-secret") }}
  jwt-secret: {{ index $existingAppSecret.data "jwt-secret" }}
  {{- else }}
  jwt-secret: {{ randAlphaNum 64 | b64enc | quote }}
  {{- end }}
{{- end }}
---
{{- if and (not .Values.database.existingPasswordSecret) (not .Values.postgresql.enabled) }}
{{- $existingDbSecret := lookup "v1" "Secret" .Release.Namespace (printf "%s-db" (include "open-tappd.fullname" .)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "open-tappd.fullname" . }}-db
  labels:
    {{- include "open-tappd.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.database.password }}
  password: {{ .Values.database.password | b64enc | quote }}
  {{- else if and $existingDbSecret $existingDbSecret.data.password }}
  password: {{ $existingDbSecret.data.password }}
  {{- else }}
  password: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
  {{- if and .Values.database.setup.adminPassword (not .Values.database.setup.existingAdminSecret) }}
  admin-password: {{ .Values.database.setup.adminPassword | b64enc | quote }}
  {{- end }}
{{- end }}
